Push images to new registry (#107)
* Add uploader script

Pushes images to registry.egi.eu egi_vm_images project

* Make the status of the biuild a json

So we can potentially do stuff with it later

* Expand secrets

* Do not check if image is already built

* Upload build to registry

* Only upload on push

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,7 +2,10 @@
 name: Build images that changed
 
 on:
-  - pull_request
+  pull_request:
+  push:
+    branches:
+      - main
 
 jobs:
   image-list:
@@ -66,6 +69,9 @@ jobs:
       - name: Deploy
         env:
           REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
+          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
+          REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
+          UPLOAD: ${{ github.event_name == 'push' }}
         run: |
           cd builder
           mkdir -p ~/.config/openstack
@@ -77,7 +83,12 @@ jobs:
                                    --oidc-access-token "$(cat .oidc_token)" \
                                    --ttl 1h --num-uses 2)"
           echo "::add-mask::$FEDCLOUD_LOCKER_TOKEN"
-          fedcloud secret put --locker-token "$FEDCLOUD_LOCKER_TOKEN" deploy "data=$REFRESH_TOKEN"
+          fedcloud secret put \
+              --locker-token "$FEDCLOUD_LOCKER_TOKEN" \
+              deploy \
+              "token=$REFRESH_TOKEN" \
+              "registry_user=$REGISTRY_USER" \
+              "registry_password=$REGISTRY_PWD"
           DEPLOY_SITE="$(yq -r .clouds.deploy.site clouds.yaml)"
           echo "DEPLOY_SITE=$DEPLOY_SITE" >> "$GITHUB_ENV"
           sed -i -e "s#%IMAGE%#${{ matrix.images }}#" cloud-init.yaml
@@ -85,6 +96,7 @@ jobs:
           sed -i -e "s/%REF%/${{ github.sha }}/" cloud-init.yaml
           sed -i -e "s/%SHORT_REF%/$(git rev-parse --short HEAD)/" cloud-init.yaml
           sed -i -e "s/%FEDCLOUD_LOCKER_TOKEN%/$FEDCLOUD_LOCKER_TOKEN/" cloud-init.yaml
+          sed -i -e "s/%UPLOAD%/$UPLOAD/" cloud-init.yaml
           # terraform!
           terraform apply -auto-approve -var-file="$DEPLOY_SITE.tfvars"
       - name: Get VM ID
@@ -121,11 +133,12 @@ jobs:
             cat "${{ steps.terraform-vm-id.outputs.stdout }}"
             echo "BUILDEOF"
           } >> "$GITHUB_OUTPUT"
-          outcome=$( (grep "^### BUILD-IMAGE: " \
-                           "${{ steps.terraform-vm-id.outputs.stdout }}" \
-                      || echo "ERROR") \
-                    | cut -f2 -d":" | cut -f1 -d"-" | tr -d " ")
-          echo "outcome=$outcome" >> "$GITHUB_OUTPUT"
+          (
+            grep "^### BUILD-RESULT: " \
+               "${{ steps.terraform-vm-id.outputs.stdout }}" \
+               || echo ': {"status": "ERROR"}' \
+          ) | cut -f2- -d":" > outcome.json
+          echo "outcome=$(jq -r .status < outcome.json)" >> "$GITHUB_OUTPUT"
       - name: Update PR with build status
         uses: actions/github-script@v7
         with:
@@ -154,7 +167,9 @@ jobs:
               repo: context.repo.repo,
               body: output
             })
-      # Now create the new files and commit them? or PR them?
+      - name: Set Status
+        if: steps.process-output.outputs.outcome != 'SUCCESS'
+        run: exit 1
       - name: Delete VM
         if: always()
         env:
