Make the status of the biuild a json
So we can potentially do stuff with it later

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -121,11 +121,12 @@ jobs:
             cat "${{ steps.terraform-vm-id.outputs.stdout }}"
             echo "BUILDEOF"
           } >> "$GITHUB_OUTPUT"
-          outcome=$( (grep "^### BUILD-IMAGE: " \
-                           "${{ steps.terraform-vm-id.outputs.stdout }}" \
-                      || echo "ERROR") \
-                    | cut -f2 -d":" | cut -f1 -d"-" | tr -d " ")
-          echo "outcome=$outcome" >> "$GITHUB_OUTPUT"
+          (
+            grep "^### BUILD-RESULT: " \
+               "${{ steps.terraform-vm-id.outputs.stdout }}" \
+               || echo ': {"status": "ERROR"}' \
+          ) | cut -f2- -d":" > outcome.json
+          echo "outcome=$(jq -r .status < outcome.json)" >> "$GITHUB_OUTPUT"
       - name: Update PR with build status
         uses: actions/github-script@v7
         with:
@@ -154,7 +155,9 @@ jobs:
               repo: context.repo.repo,
               body: output
             })
-      # Now create the new files and commit them? or PR them?
+      - name: Set Status
+        if: steps.process-output.outputs.outcome != 'SUCCESS'
+        run: exit 1
       - name: Delete VM
         if: always()
         env:
